---
title: "Performance"
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(summclust)
library(sandwich)
```

The CRV3 Jackknife estimators proposed in MNW (2022) are incredibly fast. 

```{r}
library(summclust)
library(haven)
library(sandwich)

nlswork <- read_dta("http://www.stata-press.com/data/r9/nlswork.dta")
# drop NAs at the moment
nlswork <- nlswork[, c("ln_wage", "grade", "age", "birth_yr", "union", "race", "msp", "ind_code")]
nlswork <- na.omit(nlswork)

nlswork1 <- nlswork[1:1000, ]

lm_fit <- lm(
  ln_wage ~ union +  race + msp + as.factor(birth_yr) + as.factor(age) + as.factor(grade),
  data = nlswork1)

if(requireNamespace("microbenchmark")){
  
  microbenchmark::microbenchmark(
  "sandwich" = 
    sandwich::vcovCL(
      lm_fit, 
      cluster = ~ind_code, 
      type = "HC3"
    ), 
  "CRV3J" = summclust::vcov_CR3J(
    lm_fit, 
    cluster = ~ind_code,
    type = "CRV3", 
    times = 1
  )
)
  
}
pracma::tic()
vcov_CL <- 
  sandwich::vcovCL(
    lm_fit, 
    cluster = ~ind_code, 
    type = "HC3"
  )
pracma::toc()

pracma::tic()
vcov_CR3J <- 
  summclust::vcov_CR3J(
    lm_fit, 
    cluster = ~ind_code,
    type = "CRV3"
  )
pracma::toc()
```



